### ISSUE TITLE
Where is Self's license?

### ISSUE THREAD

**Issue by L2G** [russellallen/self#43]
There are many comments that refer to the "LICENSE" file for license information, but I cannot find such a file.

**Comment by russellallen** [comment]
Is there some doc showing what Github is looking for? Our licence is 'BSD-like' but not a standard BSD licence.

**Comment by krono** [comment]
No, I have not seen something, maybe in the next days.

**Comment by Bystroushaak** [comment]
Maybe? https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository

> Most people place their license text in a file named LICENSE.txt (or LICENSE.md) in the root of the repository

Related:

- https://developer.github.com/v3/licenses/
- http://stackoverflow.com/questions/31639059/how-to-add-license-to-a-existing-github-project

**Comment by krono** [comment]
Interesting. 
I only revived this because GitHub started labeling some projects w/ their license, see for example https://github.com/pycket/pycket (top right: 

<img width="1001" alt="bildschirmfoto 2016-09-10 um 15 09 21" src="https://cloud.githubusercontent.com/assets/119279/18410676/977d9060-7768-11e6-876b-c4a4780f0a47.PNG">
