### ISSUE TITLE
(recent change) fonts are unhappy on Linux.

### ISSUE THREAD

**Issue by faried** [russellallen/self#45]
I don't think it's just fonts.  Here's an album with two screenshots: https://imgur.com/a/sKTE9

The first image is with the world built from commit 7aef6e87158b17107227404cdeca43ec9f0feab0 and the second from d5213400ba63fc8aeed1675a7fa8c7b0fe1e18ba

The snapshot I built yesterday (before I filed #44) works fine, as does Clean.snap (both with today's vm).

Also, I read #7 but I'm not sure how to influence the font the system wants to use.  I see verdana hard-coded into a bunch of places in the code.

**Comment by doublec** [comment]
Fonts are hard coded all over the place. I did some work on [getting better font support](http://bluishcoder.co.nz/2015/01/08/improving-linux-font-support-in-self.html) but have not had the time to finish it. The code is in my branch in the repository mentioned in that post.

**Comment by russellallen** [comment]
Fonts are unhappy in Linux generally for a number of reasons, but that latest screenshot is a bit of a car crash. I’ll fire up a Linux vm and see what’s happening.

**Comment by russellallen** [comment]
OK, it was because some of the recent UI improvements relied on transparent morphs, which didn't work well with the current X11 interface.

It should be fixed in the latest commit, at least in the sense of being usable even if the default font isn't particularly beautiful. Please reopen this if it doesn't work for you.
