### ISSUE TITLE
'worldBuilder.self' _RunScript doesn't work out of the box

### ISSUE THREAD

**Issue by dyba** [russellallen/self#52]
I downloaded the DMG file for Mac OS X and followed the instructions as written [here](http://handbook.selflanguage.org/4.5/buildworld.html). Unfortunately, I couldn't get the world to build. Here is the error message I got:

```
VM# 'worldBuilder.self' _RunScript
A lookup error happened while sending the message
        primitiveFailedError:Name:
to
        'worldBuilder.self'.
Subsequently, the lookup error message
        undefinedSelector:Receiver:Type:Delegatee:MethodHolder:Arguments:
was sent to
        <2>,
and was also not understood, causing the process to be aborted by the Self VM.

#0 (<error>:1): primitiveFailedError:Name: = ( | self* = 'worldBuilder.self'. :arg1 = 'ENOENT'. :arg2 = '_RunScript'. delegatee = nil. selector = 'primitiveFailedError:Name:'. | 
"undefined selector error;
this method was automatically generated by the VM."
 )


#1 (<stdin>:1): <top level expr> = ( | self* = lobby. | 'worldBuilder.self' _RunScript )
```

I am running on the El Capitan version of OS X, version 10.11.1.

**Comment by russellallen** [comment]
Hi dyba,
Did you run the Self vm from the objects directory? i.e. is 'worldBuilder.self' in the current working directory?
Also, how did you install the Self vm itself? 
Russell

**Comment by dyba** [comment]
@russellallen Thanks for the quick reply! I downloaded the DMG and moved that to my Applications folder. Next, I created an Empty VM. That brought up a new Terminal window with the VM prompt. After that, I typed:

```
_Spy: true
```

I had to do that twice for whatever reason because the first time, it said ```false```. Finally, I ran the command:

```
'worldBuilder.self' _RunScript
```

That's when I got the error I mentioned.

Where is the objects directory?

**Comment by dyba** [comment]
It looks like Self is only supported on Mac OS X 10.7. I'm on 10.11. So perhaps the DMG isn't packaged for the latest version of Mac OS X? I read [this thread](https://groups.yahoo.com/neo/groups/self-interest/conversations/messages/3264) which mentions I can compile Self by hand so that it doesn't depend on the Mac OS X interface and instead run Self using X11. Would that be a better option for me?

And if so, how exactly would I compile Self to use X11?

**Comment by russellallen** [comment]
Self should work fine on 10.11 for your purposes. 

I think there is a little confusion. I'll try to explain.

There are two ways to run the full Self environment on the Self VM. 

The most common way is to use the prebuilt environment. This is in your dmg file, it's called "Clean.snap". To run it, drag the snapshot to your local filesystem (e.g. the Desktop). Then from the Self Control.app, select "Choose Snapshot..." and select the Clean.snap file from the dialog. This should run the environment, which should open a window with Morphic running. If you know Smalltalk, then the .snap file is the equivalent of an .images file. Otherwise, think of it as being like a VMWare image - a frozen snapshot of the state of the system.

The second way is to build the environment from the original Self source files. These aren't distributed in the DMG file because they are large. Instead you need to clone the Self git repository. In that repository is an 'objects' directory. The directions you were following assumed you had already obtained that 'objects' directory, which as the 'worldBuilder.self' file in it. Sending the _RunScript message to that file failed for you because the file was not in your current directory.

Does this make sense?

**Comment by dyba** [comment]
Yes! :tada: Thank you for the explanation. I totally ignored the Clean.snap file because it didn't look useful. I get it now snap is short for snapshot. :facepunch: myself. I wonder if others have had a similar experience.
