### ISSUE TITLE
`joinUsing:` failed to join empty sequences

### ISSUE THREAD

**Issue by dram** [russellallen/self#98]
`joinUsing:` will fail with `empty collection` error if trying to join an empty sequence, e.g.:

```
sequence copy joinUsing: '&'
```

I think this behavior is not quite right.

**Comment by russellallen** [comment]
Doesn't sound right, no.  The problem comes that my naive implementation of joinUsing: returns a collection of the type of the first element of the receiver, i.e. 

`('a' & 'b') asSequence joinUsing: 'c' ---> a string 'abc' because 'a' is a string.`

I have changed it to return a collection of the type of the argument, i.e.

`('a' & 'b') asSequence joinUsing: 'c' ---> a string 'abc' because 'c' is a string.`

This means that:

`sequence copy joinUsing: '&' ---> a string '' because '&' is a string`

Does this sound reasonable?

**Comment by dram** [comment]
Yes, I think it's reasonable.

Following are behaviors of some other languages:

1. [Open Dylan](http://opendylan.org/documentation/library-reference/common-dylan/common-extensions.html#common-dylan:common-extensions:join): If sequence is empty, result type will be type of the separator, otherwise, result type will be same as the original one.
2. [Ruby](https://ruby-doc.org/core-2.2.0/Array.html#join-method): Always returns string, will convert every elements of iterator to string firstly.
3. [Python](https://docs.python.org/2/library/stdtypes.html#str.join): `join` is a method of `str`, so it's reasonable to always return string.

[Dart](https://api.dartlang.org/stable/1.20.1/dart-core/Iterable/join.html) is same as Ruby.

I think use type of `separator` as result type is enough, it covers *joining string* use case, and is more flexible than Ruby and Dart. Open Dylan's behavior is a bit too complex.

**Comment by russellallen** [comment]
Cool, in that case I think we're done.
